### ISSUE TITLE
serverManager controls fans but logs show SIGSEGV for ipmitool

### ISSUE THREAD

**Issue by vonswoopington** [Danielv123/serverManager#93]
**Environment:**  
- Platform: Unraid OS 7.1.4
- Deployment: Docker Compose stack using Docker Compose Manager
- Image: `ghcr.io/danielv123/servermanager:latest`  
- Hardware: Dell R730xd  
- Stack config:  
  - Port mapping: `8083:8080`  
  - Volume mapping: ` /mnt/user/appdata/serverManager:/usr/src/app/data`  
  - Additional container: `ouroboros` for auto‑updates  

---

**Steps to Reproduce:**  
1. Deploy the stack in Unraid using Docker Compose.  
2. In the UI, add fan curves for the Dell R730xd.  
3. Navigate on the dashboard: the sensor data (temperatures, wattage, fan speeds) appears correctly.  
4. Open the **Logs** view.  
5. Observe errors in the logs (see attached/excerpt below).

---

**Expected Behavior:**  
- The UI should show correct sensor data.  
- The logs should reflect normal operations without error entries.

---

**Actual Behavior:**  
- UI shows correct sensor data (temperatures, wattage, fans).  
- However, the logs display error messages indicating something is wrong behind the scenes.

---

**Impact / Severity:**  
- **Medium** - The UI appears to work, but the log errors suggest hidden issues that may affect reliability or future operations.

---

**Attachments / Additional Info:**  
- Log excerpt:  

```
Error: Command failed: ipmitool -I lanplus -H idrac.home.lan -U idrac -P password sensor  
    at genericNodeError (node:internal/errors:985:15)  
    at wrappedFn (node:internal/errors:539:14)  
    at ChildProcess.exithandler (node:child_process:417:12)  
    at ChildProcess.emit (node:events:508:28)  
    at maybeClose (node:internal/child_process:1101:16)  
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {  
  code: null,  
  killed: false,  
  signal: 'SIGSEGV',  
  cmd: 'ipmitool -I lanplus -H idrac.home.lan -U idrac -P password sensor'  
}
```

Love the tool so far. Any ideas on what could be causing this?

**Comment by Danielv123** [comment]
Uh, thats a weird one. Looks like ipmitool is screwed up somehow?

Can you try with 

    docker pull ghcr.io/danielv123/servermanager@sha256:b8399fb2b1a067c2d8e6731b43daa739ce2593be3cbe8f34d1770b590c1c4009

this is the old image which I know for a fact has been working well for a long time (except for some config bugs, but those aren't relevant since you have already configured it)

**Comment by vonswoopington** [comment]
> Uh, thats a weird one. Looks like ipmitool is screwed up somehow?
> 
> Can you try with
> 
> ```
> docker pull ghcr.io/danielv123/servermanager@sha256:b8399fb2b1a067c2d8e6731b43daa739ce2593be3cbe8f34d1770b590c1c4009
> ```
> 
> this is the old image which I know for a fact has been working well for a long time (except for some config bugs, but those aren't relevant since you have already configured it)

I tested on windows and on Unraid and I did not see any ipmitool errors in the logs with this version.

**Comment by Quentin-SPINDLER** [comment]
I have the same issue, same logs, using Dockge on truenas, on a Dell T430. CPU Temperature was not displayed on the UI and the fan control was not reacting to the temperature increase. 
I can confirm that the "ghcr.io/danielv123/servermanager@sha256:b8399fb2b1a067c2d8e6731b43daa739ce2593be3cbe8f34d1770b590c1c4009" does not have the issue and working fine.
Thanks for the workaround and for the good work :)

**Comment by Danielv123** [comment]
@vonswoopington @Quentin-SPINDLER I just published ghcr.io/danielv123/servermanager:sha-42079eb199ef5332d8239cc0bd812e7ed9a95711 (available at :latest) where I reverted the changes made to the runtime container. I don't have a server running with ipmi to test with at the moment - could either of you check if this version resolves the issue?

**Comment by vonswoopington** [comment]
> [@vonswoopington](https://github.com/vonswoopington) [@Quentin-SPINDLER](https://github.com/Quentin-SPINDLER) I just published ghcr.io/danielv123/servermanager:sha-42079eb199ef5332d8239cc0bd812e7ed9a95711 (available at :latest) where I reverted the changes made to the runtime container. I don't have a server running with ipmi to test with at the moment - could either of you check if this version resolves the issue?

I tried it but I am still getting the same issue.

**Comment by Quentin-SPINDLER** [comment]
> [@vonswoopington](https://github.com/vonswoopington) [@Quentin-SPINDLER](https://github.com/Quentin-SPINDLER) I just published ghcr.io/danielv123/servermanager:sha-42079eb199ef5332d8239cc0bd812e7ed9a95711 (available at :latest) where I reverted the changes made to the runtime container. I don't have a server running with ipmi to test with at the moment - could either of you check if this version resolves the issue?

Tried both ghcr.io/danielv123/servermanager:sha-42079eb199ef5332d8239cc0bd812e7ed9a95711 and :latest just to be sure, I still have the issue.

**Comment by Danielv123** [comment]
Well darnit. Looks like some environment issue with the image. I will leave this issue open in case someone running ipmi want to take a stab at fixing the docker image - for now I have reverted the :latest tag to the old image.
